### ISSUE TITLE
secure routes

### ISSUE THREAD

**Issue by mattgi** [bentojs/api-user#8]
Presently an anon can view all users.

Most routes in this module should only be accessible to owner and admins. Can this be configurable?

Example: (but all routes should be considered)

```
Route.resource('users', 'User/UsersController', {
  create : {
    policy : config.policies.create : null,
    params : config.params ? config.params : null
  },
  update : {
    policy : config.policies.update : 'isAuthenticated',
    params : config.params ? config.params.filter((val) => { return val !== 'password'; }) : null
  }
});
```

**Comment by Kodemon** [comment]
It shouldn't be a problem moving the resource configuration to the default.js which can then be modified per project.
